### PR TITLE
Add missing video link

### PR DESCRIPTION
**Pull request by MatBon01**
I noticed that the video you were referring to was not linked.

This also uncovered a problem with links in your paragraphs in info classes

### CODE REVIEW

**Comment by MatBon01** [comment]
I saw that the link was missing and so thought this would be a nice opportunity to give you a first taste of public engagement. I understand this is a deeply personal project and a safe space for autistic woman (I am not an autistic woman) so if you want to take my issue/fix and implement it yourself to keep the credit I would strongly support that. Otherwise it would be an honour to contribute to a project that is trying to do good.

**Comment by MatBon01** [comment]
@ElysiaW I have removed the z value -1 from the .info p styling because that was the quickest way to fix the problem, I tested and could not find any issues but you are the one who wrote it so probably have more of an idea of what the issue might be, maybe try switching to the repo/branch locally and testing to make sure I don't break your menu bar?

**Comment by MatBon01** [comment]
Feel no pressure to even consider this pull request if you want to keep your great prize winning website exactly as it was (especially with my change to your clearly thought out style sheet) - just my way of showing you your work is appreciated

**Comment by MatBon01** [comment]
> @ElysiaW I have removed the z value -1 from the .info p styling because that was the quickest way to fix the problem, I tested and could not find any issues but you are the one who wrote it so probably have more of an idea of what the issue might be, maybe try switching to the repo/branch locally and testing to make sure I don't break your menu bar?

^^
@ElysiaW

**Comment by ElysiaW** [comment]
> > @ElysiaW I have removed the z value -1 from the .info p styling because that was the quickest way to fix the problem, I tested and could not find any issues but you are the one who wrote it so probably have more of an idea of what the issue might be, maybe try switching to the repo/branch locally and testing to make sure I don't break your menu bar?
> 
> ^^ @ElysiaW

I haven't run into any issues while testing so far but I will look deeper into the classes to make sure nothing will go wrong in the future. Thanks a lot for the help I really appreciate it :)

@MatBon01

**Comment by MatBon01** [comment]
> > > @ElysiaW I have removed the z value -1 from the .info p styling because that was the quickest way to fix the problem, I tested and could not find any issues but you are the one who wrote it so probably have more of an idea of what the issue might be, maybe try switching to the repo/branch locally and testing to make sure I don't break your menu bar?
> > 
> > 
> > ^^ @ElysiaW
> 
> I haven't run into any issues while testing so far but I will look deeper into the classes to make sure nothing will go wrong in the future. Thanks a lot for the help I really appreciate it :)
> 
> @MatBon01

No worries - it's an amazing piece of work and I'm sure the first of many so I'm happy to contribute. It's very personal to you so I care about making sure it doesn't break that's why I just emphasised checking :D

**Comment by MatBon01** [comment]
> > > > @ElysiaW I have removed the z value -1 from the .info p styling because that was the quickest way to fix the problem, I tested and could not find any issues but you are the one who wrote it so probably have more of an idea of what the issue might be, maybe try switching to the repo/branch locally and testing to make sure I don't break your menu bar?
> > > 
> > > 
> > > ^^ @ElysiaW
> > 
> > 
> > I haven't run into any issues while testing so far but I will look deeper into the classes to make sure nothing will go wrong in the future. Thanks a lot for the help I really appreciate it :)
> > @MatBon01
> 
> No worries - it's an amazing piece of work and I'm sure the first of many so I'm happy to contribute. It's very personal to you so I care about making sure it doesn't break that's why I just emphasised checking

@ElysiaW

**Pull request merged**
